# Generated by Django 3.0.2 on 2020-03-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Covid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='profiles')),
                ('Full_Name', models.CharField(default='', max_length=50)),
                ('Age', models.CharField(default='', max_length=20)),
                ('Gender', models.CharField(default='', max_length=20)),
                ('Fever', models.CharField(default='', max_length=25)),
                ('BodyPain', models.CharField(default='', max_length=20)),
                ('ResidencePlace', models.CharField(default='', max_length=20)),
                ('RunnyNose', models.CharField(default='', max_length=20)),
                ('Cough', models.CharField(default='', max_length=20)),
                ('Breath', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
