# Generated by Django 3.0.2 on 2020-03-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Covid', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covid',
            name='ResidencePlace',
        ),
        migrations.AddField(
            model_name='covid',
            name='Email',
            field=models.CharField(default='', max_length=25),
        ),
    ]
