# Generated by Django 3.0.2 on 2020-03-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Covid', '0002_auto_20200322_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='covid',
            name='InfectionProb',
            field=models.CharField(default='', max_length=20),
        ),
    ]
