# Generated by Django 3.0.2 on 2020-03-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Covid', '0003_covid_infectionprob'),
    ]

    operations = [
        migrations.AddField(
            model_name='covid',
            name='OTP',
            field=models.CharField(default='', max_length=20),
        ),
    ]
